---

# Clone Backup & Discovery Scripts from github
- name: Clone lvm-restic-backup
  ansible.builtin.get_url:
    url: 'https://raw.githubusercontent.com/sebastian13/lvm-restic-backup/master/lvm-restic-backup.sh'
    dest: /usr/bin/lvm-rescript
    mode: "0700"
    force: true
  when: "'local' not in ansible_run_tags"

# Alternatively, copy a local copy if tag 'local' is defined
- name: Copy the lvm-restic-backup.sh
  ansible.builtin.copy:
    src: lvm-restic-backup.sh
    dest: /usr/bin/lvm-rescript
    mode: "0700"
  tags:
    - never
    - local

- name: Create /etc/zabbix/scripts
  ansible.builtin.file:
    path: /etc/zabbix/scripts
    state: directory
    mode: "0755"

- name: Download discovery script
  ansible.builtin.get_url:
    url: 'https://raw.githubusercontent.com/sebastian13/zabbix-template-rescript/master/scripts/rescript-lvm-discovery.pl'
    dest: /etc/zabbix/scripts/
    mode: "0700"
    force: true
  when: "'local' not in ansible_run_tags"

# Alternatively, copy a local copy if tag 'local' is defined
- name: Copy discovery script
  ansible.builtin.copy:
    src: rescript-lvm-discovery.pl
    dest: /etc/zabbix/scripts/
    mode: "0700"
  tags:
    - never
    - local

- name: Create restic directory
  ansible.builtin.file:
    path: /etc/restic
    state: directory
    mode: "0755"

- name: Copy exclusions file
  ansible.builtin.copy:
    src: "exclude.txt"
    dest: "/etc/restic/exclude.txt"
    mode: "0644"
    force: true
    backup: true

- name: Deploy lvm backup scripts
  ansible.builtin.template:
    src: 'lvm-restic.sh.j2'
    dest: '/etc/restic/{{ item.rescript_repo_name }}.sh'
    mode: "0744"
    force: true
  with_items: '{{ lvm_rescript }}'

- name: Create lvm cronjobs
  ansible.builtin.cron:
    name: "LVM Rescript Backup to repo {{ item.rescript_repo_name }}"
    minute: "{{ item.rescript_lvm_cron_minute | default(15 | random(seed=inventory_hostname)) }}"
    hour: "{{ item.rescript_lvm_cron_hour | default(5 | random(seed=inventory_hostname)) }}"
    weekday: "{{ item.rescript_lvm_cron_weekday | default('*') }}"
    job: "{{ item.rescript_lvm_cron_job | default('chronic /etc/restic/' + item.rescript_repo_name + '.sh') }}"
    state: "{{ item.rescript_lvm_cron_state | default('present') }}"
  with_items: "{{ lvm_rescript }}"
  no_log: false
